[workspace]
resolver = "3"
members = [
	"crates/tool/tool-core",
	"crates/tool/toolctl",
	"crates/tool/tool-installer",
	"crates/migration/upstream-migration-planner",
]

[workspace.package]
edition = "2024"
authors = ["on9au <151502370+on9au@users.noreply.github.com>"]

[workspace.dependencies]
tool-core = { path = "crates/tool/tool-core" }

anyhow = "1.0"
clap = { version = "4.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
