[package]
name = "reaper"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
anyhow.workspace = true
walkdir.workspace = true

[target.'cfg(windows)'.dependencies]
windows ={ workspace = true, features = [
    "Win32_System_RestartManager",
    "Win32_System_Threading",
    "Win32_Foundation",
] }